// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkxsbcseikwbfzlcwywf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhreHNiY3NlaWt3YmZ6bGN3eXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDYyOTAsImV4cCI6MjA2MDQ4MjI5MH0.qAlj2tFJoVAAg-3Zfom1bnVRbffLBfcx-bUmIXKGSdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);